<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Ebook;
use Illuminate\Database\Seeder;

class EbookSeeder extends Seeder
{
    public function run(): void
    {
        $ebooks = [
            [
                'title' => 'Le Château de verre',
                'author' => 'Jean Dupont',
                'description' => 'Une famille hors du commun tente de survivre dans un monde qui les rejette. Un récit poignant sur la résilience et l\'espoir.',
                'isbn' => '978-2-07-012345-6',
                'total_pages' => 352,
                'preview_pages' => 15,
                'is_featured' => true,
                'categories' => ['Romance', 'Thriller'],
            ],
            [
                'title' => 'Étoiles sans lendemain',
                'author' => 'Marie Laurent',
                'description' => 'Dans un futur proche, l\'humanité colonise Mars. Une astronaute doit choisir entre sa mission et son cœur.',
                'isbn' => '978-2-07-012346-3',
                'total_pages' => 420,
                'preview_pages' => 12,
                'is_featured' => true,
                'categories' => ['Science-Fiction', 'Romance'],
            ],
            [
                'title' => 'L\'Ombre du passé',
                'author' => 'Pierre Moreau',
                'description' => 'Un inspecteur obsédé par une affaire non résolue remet tout en question quand de nouveaux indices refont surface.',
                'isbn' => '978-2-07-012347-0',
                'total_pages' => 380,
                'preview_pages' => 10,
                'is_featured' => true,
                'categories' => ['Polar', 'Thriller'],
            ],
            [
                'title' => 'Les Royaumes oubliés',
                'author' => 'Sophie Merlin',
                'description' => 'Une guerrière doit rassembler les artefacts dispersés pour empêcher le retour d\'un ancien mal.',
                'isbn' => '978-2-07-012348-7',
                'total_pages' => 512,
                'preview_pages' => 20,
                'is_featured' => true,
                'categories' => ['Fantasy'],
            ],
            [
                'title' => 'Une vie',
                'author' => 'Claire Bernard',
                'description' => 'Biographie intime d\'une artiste qui a marqué son époque. De l\'enfance à la gloire, un parcours sans concession.',
                'isbn' => '978-2-07-012349-4',
                'total_pages' => 288,
                'preview_pages' => 10,
                'is_featured' => false,
                'categories' => ['Biographie'],
            ],
            [
                'title' => 'Le Dernier Train',
                'author' => 'Thomas Keller',
                'description' => 'En 1944, un convoi s\'arrête en pleine campagne. Ce qui se passe à bord changera la vie de tous les passagers.',
                'isbn' => '978-2-07-012350-0',
                'total_pages' => 310,
                'preview_pages' => 12,
                'is_featured' => true,
                'categories' => ['Histoire', 'Thriller'],
            ],
            [
                'title' => 'Réveille ton potentiel',
                'author' => 'Dr. Anne Lefebvre',
                'description' => 'Des méthodes concrètes pour dépasser ses limites et construire la vie que l\'on mérite.',
                'isbn' => '978-2-07-012351-7',
                'total_pages' => 220,
                'preview_pages' => 8,
                'is_featured' => false,
                'categories' => ['Développement personnel'],
            ],
            [
                'title' => 'Mystère à Venise',
                'author' => 'Lucie Vanni',
                'description' => 'Un meurtre dans un palais au bord du canal. Une journaliste et un commissaire italien mènent l\'enquête.',
                'isbn' => '978-2-07-012352-4',
                'total_pages' => 340,
                'preview_pages' => 14,
                'is_featured' => false,
                'categories' => ['Polar', 'Romance'],
            ],
            [
                'title' => 'Au-delà du miroir',
                'author' => 'Nicolas Storm',
                'description' => 'Un physicien découvre un passage vers un univers parallèle. Mais ce qu\'il y trouve menace le nôtre.',
                'isbn' => '978-2-07-012353-1',
                'total_pages' => 398,
                'preview_pages' => 15,
                'is_featured' => true,
                'categories' => ['Science-Fiction', 'Thriller'],
            ],
            [
                'title' => 'Le Jardin des sortilèges',
                'author' => 'Élise Corbeau',
                'description' => 'Une apprentie sorcière doit protéger un jardin magique convoité par des forces obscures.',
                'isbn' => '978-2-07-012354-8',
                'total_pages' => 265,
                'preview_pages' => 10,
                'is_featured' => false,
                'categories' => ['Fantasy', 'Jeunesse'],
            ],
            [
                'title' => 'Napoléon : le destin et la légende',
                'author' => 'François Durand',
                'description' => 'Une relecture moderne du parcours de Napoléon Bonaparte, de la Révolution à Sainte-Hélène.',
                'isbn' => '978-2-07-012355-5',
                'total_pages' => 580,
                'preview_pages' => 25,
                'is_featured' => true,
                'categories' => ['Histoire', 'Biographie'],
            ],
            [
                'title' => 'Sans un mot',
                'author' => 'Camille Roux',
                'description' => 'Elle a tout quitté pour recommencer ailleurs. Mais le passé la rattrape au moment où elle s\'y attend le moins.',
                'isbn' => '978-2-07-012356-2',
                'total_pages' => 320,
                'preview_pages' => 12,
                'is_featured' => false,
                'categories' => ['Romance', 'Thriller'],
            ],
            [
                'title' => 'Le Réseau Phoenix',
                'author' => 'Marc Vidal',
                'description' => 'Un hackeur génial est recruté par une agence secrète. Chaque mission le rapproche d\'une vérité terrifiante.',
                'isbn' => '978-2-07-012357-9',
                'total_pages' => 410,
                'preview_pages' => 18,
                'is_featured' => true,
                'categories' => ['Thriller', 'Science-Fiction'],
            ],
            [
                'title' => 'L\'Épée des ombres',
                'author' => 'Raphaël Thorn',
                'description' => 'Dans un monde où la magie a été bannie, un guerrier détient la dernière arme capable de rétablir l\'équilibre.',
                'isbn' => '978-2-07-012358-6',
                'total_pages' => 445,
                'preview_pages' => 15,
                'is_featured' => false,
                'categories' => ['Fantasy'],
            ],
            [
                'title' => 'Petit guide du bonheur',
                'author' => 'Julie Manceau',
                'description' => 'Des exercices simples et des réflexions pour cultiver le bonheur au quotidien.',
                'isbn' => '978-2-07-012359-3',
                'total_pages' => 180,
                'preview_pages' => 8,
                'is_featured' => false,
                'categories' => ['Développement personnel'],
            ],
            [
                'title' => 'Le Manuscrit du Caire',
                'author' => 'Antoine Besson',
                'description' => 'Un manuscrit ancien refait surface et entraîne une course contre la montre entre érudits et trafiquants.',
                'isbn' => '978-2-07-012360-9',
                'total_pages' => 390,
                'preview_pages' => 14,
                'is_featured' => true,
                'categories' => ['Thriller', 'Histoire'],
            ],
            [
                'title' => 'Premier amour',
                'author' => 'Léa Fontaine',
                'description' => 'L\'histoire d\'un premier amour qui marque toute une vie. Tendresse, maladresse et souvenirs.',
                'isbn' => '978-2-07-012361-6',
                'total_pages' => 240,
                'preview_pages' => 10,
                'is_featured' => false,
                'categories' => ['Romance', 'Jeunesse'],
            ],
            [
                'title' => 'Mission Proxima',
                'author' => 'Dr. Serge Kovalev',
                'description' => 'La première mission habitée vers Proxima du Centaure. Un voyage sans retour pour l\'équipage.',
                'isbn' => '978-2-07-012362-3',
                'total_pages' => 468,
                'preview_pages' => 20,
                'is_featured' => true,
                'categories' => ['Science-Fiction'],
            ],
            [
                'title' => 'Meurtres en série',
                'author' => 'Commissaire Dumas',
                'description' => 'Trois corps, un seul modus operandi. La brigade criminelle doit trouver le lien avant le prochain meurtre.',
                'isbn' => '978-2-07-012363-0',
                'total_pages' => 355,
                'preview_pages' => 12,
                'is_featured' => false,
                'categories' => ['Polar', 'Thriller'],
            ],
            [
                'title' => 'La Tour des mages',
                'author' => 'Céline Aube',
                'description' => 'Une jeune mage doit gravir les étages de la tour pour obtenir son diplôme. Chaque niveau réserve des épreuves mortelles.',
                'isbn' => '978-2-07-012364-7',
                'total_pages' => 398,
                'preview_pages' => 16,
                'is_featured' => true,
                'categories' => ['Fantasy', 'Jeunesse'],
            ],
            [
                'title' => 'Celle qui a osé',
                'author' => 'Hélène Martel',
                'description' => 'Portrait d\'une exploratrice du XIXe siècle qui a bravé les conventions pour vivre ses rêves.',
                'isbn' => '978-2-07-012365-4',
                'total_pages' => 310,
                'preview_pages' => 11,
                'is_featured' => false,
                'categories' => ['Biographie', 'Histoire'],
            ],
            [
                'title' => 'L\'Art de dire non',
                'author' => 'Patrick Rousseau',
                'description' => 'Apprendre à poser des limites sans culpabilité. Guide pratique pour affirmer ses choix.',
                'isbn' => '978-2-07-012366-1',
                'total_pages' => 195,
                'preview_pages' => 9,
                'is_featured' => false,
                'categories' => ['Développement personnel'],
            ],
            [
                'title' => 'Nuit blanche à Paris',
                'author' => 'Juliette Lenoir',
                'description' => 'Une nuit, une rencontre, une ville qui ne dort jamais. Un roman choral sur le hasard et les destins qui se croisent.',
                'isbn' => '978-2-07-012367-8',
                'total_pages' => 278,
                'preview_pages' => 10,
                'is_featured' => false,
                'categories' => ['Romance'],
            ],
            [
                'title' => 'L\'Algorithme fatal',
                'author' => 'Ing. Laura Chen',
                'description' => 'Une IA conçue pour optimiser la justice déraille. Qui contrôle encore le système ?',
                'isbn' => '978-2-07-012368-5',
                'total_pages' => 385,
                'preview_pages' => 14,
                'is_featured' => true,
                'categories' => ['Science-Fiction', 'Thriller'],
            ],
            [
                'title' => 'Le Dernier Témoin',
                'author' => 'Maître Dubois',
                'description' => 'Un avocat défend un accusé dont le seul alibi est un témoin qui a disparu. La vérité est ailleurs.',
                'isbn' => '978-2-07-012369-2',
                'total_pages' => 332,
                'preview_pages' => 13,
                'is_featured' => false,
                'categories' => ['Polar'],
            ],
            [
                'title' => 'Les Enfants de la forêt',
                'author' => 'Marine Forest',
                'description' => 'Dans une forêt enchantée, des enfants découvrent qu\'ils ont un pouvoir : parler aux arbres.',
                'isbn' => '978-2-07-012370-8',
                'total_pages' => 215,
                'preview_pages' => 10,
                'is_featured' => false,
                'categories' => ['Fantasy', 'Jeunesse'],
            ],
            [
                'title' => '1914-1918 : Ce qu\'ils ont vécu',
                'author' => 'Historien Garnier',
                'description' => 'Lettres et journaux de poilus pour raconter la Grande Guerre de l\'intérieur.',
                'isbn' => '978-2-07-012371-5',
                'total_pages' => 420,
                'preview_pages' => 18,
                'is_featured' => true,
                'categories' => ['Histoire'],
            ],
            [
                'title' => 'Deux cœurs, une île',
                'author' => 'Romane Saint-Clair',
                'description' => 'Elle hérite d\'une maison sur une île bretonne. Lui est le voisin taciturne. L\'été va tout changer.',
                'isbn' => '978-2-07-012372-2',
                'total_pages' => 298,
                'preview_pages' => 12,
                'is_featured' => false,
                'categories' => ['Romance'],
            ],
            [
                'title' => 'Colonie Alpha',
                'author' => 'Alex Rivera',
                'description' => 'Sur une exoplanète, la colonie Alpha signale des anomalies. La mission de secours découvre l\'impensable.',
                'isbn' => '978-2-07-012373-9',
                'total_pages' => 412,
                'preview_pages' => 16,
                'is_featured' => true,
                'categories' => ['Science-Fiction'],
            ],
            [
                'title' => 'Le Cercle des menteurs',
                'author' => 'Capitaine Leroy',
                'description' => 'Dans un lycée huppé, un élève est retrouvé mort. Tous ont quelque chose à cacher.',
                'isbn' => '978-2-07-012374-6',
                'total_pages' => 368,
                'preview_pages' => 14,
                'is_featured' => false,
                'categories' => ['Polar', 'Thriller'],
            ],
            [
                'title' => 'Le Grimoire interdit',
                'author' => 'Morgane Black',
                'description' => 'Un grimoire volé à une bibliothèque secrète déclenche une quête entre mondes réels et surnaturels.',
                'isbn' => '978-2-07-012375-3',
                'total_pages' => 425,
                'preview_pages' => 17,
                'is_featured' => true,
                'categories' => ['Fantasy', 'Thriller'],
            ],
        ];

        $categoryModels = Category::all()->keyBy('name');

        foreach ($ebooks as $i => $data) {
            $categories = $data['categories'];
            unset($data['categories']);

            $slug = \Illuminate\Support\Str::slug($data['title']);
            $coverUrl = 'https://picsum.photos/seed/' . ($i + 1) . '/300/450';
            $pdfPath = 'placeholders/ebook-' . ($i + 1) . '.pdf';

            $ebook = Ebook::firstOrCreate(
                ['slug' => $slug],
                array_merge($data, [
                    'cover_image_url' => $coverUrl,
                    'pdf_file_path' => $pdfPath,
                    'pdf_file_size' => rand(500000, 5000000),
                    'published_at' => now()->subDays(rand(5, 180)),
                    'is_active' => true,
                ])
            );

            foreach ($categories as $catName) {
                if ($categoryModels->has($catName)) {
                    $ebook->categories()->syncWithoutDetaching([$categoryModels->get($catName)->id]);
                }
            }
        }
    }
}
